swagger: '2.0'
info:
  description: An API for Flight search
  version: 0.0.1-SNAPSHOT
  title: Flight Search API
  contact:
    name: Akinalp Fidan
    url: '05546003030'
    email: akinalpfdn@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: localhost:8081
basePath: /
tags:
  - name: auth-controller
    description: Auth Controller
  - name: data-controller
    description: Data Controller
  - name: flight-controller
    description: Flight Controller
paths:
  /auth/getToken:
    get:
      tags:
        - auth-controller
      summary: getToken
      operationId: getTokenUsingGET
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /data/getAirports:
    get:
      tags:
        - data-controller
      summary: getAirports
      operationId: getAirportsUsingGET
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Airport'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /data/getFlights:
    get:
      tags:
        - data-controller
      summary: getFlights
      operationId: getFlightsUsingGET
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Flight Search API Documentation'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /flight/getFlightInfo:
    get:
      tags:
        - flight-controller
      summary: A method for finding suitable flight with given parameters
      operationId: getFlightInfoUsingGET
      produces:
        - '*/*'
      parameters:
        - name: arrivalLocation
          in: query
          description: arrivalLocation
          required: true
          type: string
        - name: Authorization
          in: header
          description: Authorization
          required: true
          type: string
        - name: departureDate
          in: query
          description: departureDate
          required: true
          type: string
        - name: departureLocation
          in: query
          description: departureLocation
          required: true
          type: string
        - name: returnDate
          in: query
          description: returnDate
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResultDto'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
definitions:
  Airport:
    type: object
    properties:
      city:
        type: string
      id:
        type: integer
        format: int64
    title: Airport
  Flight Search API Documentation:
    type: object
    properties:
      departureAirport:
        description: Name Of Departure City
        $ref: '#/definitions/Airport'
      departureDate:
        type: string
        format: date-time
        description: Date and time of departure
      destinationAirport:
        description: Name Of Destination City
        $ref: '#/definitions/Airport'
      id:
        type: integer
        format: int64
      price:
        type: number
        format: float
        description: Price of the Ticket
      returnDate:
        type: string
        format: date-time
        description: Date and time of arrival
    title: Flight Search API Documentation
    description: Model
  ResultDto:
    type: object
    properties:
      result:
        type: object
      smessage:
        type: string
      status:
        type: string
        enum:
          - ACCEPTED
          - ALREADY_REPORTED
          - BAD_GATEWAY
          - BAD_REQUEST
          - BANDWIDTH_LIMIT_EXCEEDED
          - CHECKPOINT
          - CONFLICT
          - CONTINUE
          - CREATED
          - DESTINATION_LOCKED
          - EXPECTATION_FAILED
          - FAILED_DEPENDENCY
          - FORBIDDEN
          - FOUND
          - GATEWAY_TIMEOUT
          - GONE
          - HTTP_VERSION_NOT_SUPPORTED
          - IM_USED
          - INSUFFICIENT_SPACE_ON_RESOURCE
          - INSUFFICIENT_STORAGE
          - INTERNAL_SERVER_ERROR
          - I_AM_A_TEAPOT
          - LENGTH_REQUIRED
          - LOCKED
          - LOOP_DETECTED
          - METHOD_FAILURE
          - METHOD_NOT_ALLOWED
          - MOVED_PERMANENTLY
          - MOVED_TEMPORARILY
          - MULTIPLE_CHOICES
          - MULTI_STATUS
          - NETWORK_AUTHENTICATION_REQUIRED
          - NON_AUTHORITATIVE_INFORMATION
          - NOT_ACCEPTABLE
          - NOT_EXTENDED
          - NOT_FOUND
          - NOT_IMPLEMENTED
          - NOT_MODIFIED
          - NO_CONTENT
          - OK
          - PARTIAL_CONTENT
          - PAYLOAD_TOO_LARGE
          - PAYMENT_REQUIRED
          - PERMANENT_REDIRECT
          - PRECONDITION_FAILED
          - PRECONDITION_REQUIRED
          - PROCESSING
          - PROXY_AUTHENTICATION_REQUIRED
          - REQUESTED_RANGE_NOT_SATISFIABLE
          - REQUEST_ENTITY_TOO_LARGE
          - REQUEST_HEADER_FIELDS_TOO_LARGE
          - REQUEST_TIMEOUT
          - REQUEST_URI_TOO_LONG
          - RESET_CONTENT
          - SEE_OTHER
          - SERVICE_UNAVAILABLE
          - SWITCHING_PROTOCOLS
          - TEMPORARY_REDIRECT
          - TOO_EARLY
          - TOO_MANY_REQUESTS
          - UNAUTHORIZED
          - UNAVAILABLE_FOR_LEGAL_REASONS
          - UNPROCESSABLE_ENTITY
          - UNSUPPORTED_MEDIA_TYPE
          - UPGRADE_REQUIRED
          - URI_TOO_LONG
          - USE_PROXY
          - VARIANT_ALSO_NEGOTIATES
    title: ResultDto
